pipeline {	
	agent any
  
stages {
		stage('Unit Test') {
			steps {
				dir {"node"}{
					sh "npm test"
			  }
			}
		}
		stage('Static code analysis') {
				steps {
				    sh '''
					      echo "Unit testing"
				    '''
			}
		}
  	}
} 